- name: start the container
  command: docker run -t -d -p 80:80 web:latest 
      

- name: Check if container is running
  shell: docker ps
  register: output

- name: debug the output 
  debug: 
    var: output

    
     